구독권 조회 API
wecode-bootcamp-korea/49-3rd-WEE.T-backend pull request #12
Opened 2023-10-21 08:34 UTC by B3lla0

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, <br> 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.

- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?

  유저가 구독 페이지에 접근 시 현재 구독중인지의 여부와 판매중인 구독권의 종류를 확인할 수 있습니다.

- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?

  유저가 이미 구독중일경우 구독권 잔여 여부를 표기하여 중복 구매 방지

<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 상세 내역을 적어주세요.
 
  구독권 조회 기능 추가

- 토큰유무 체크 후, 토큰을 보유 시에만 이용 가능
- 현재 유저가 구독중인지의 여부를 체크
- 서비스 중인 구독권 종류를 조회

<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. 
<br />

![image](https://github.com/wecode-bootcamp-korea/49-3rd-WEE.T-backend/assets/108120358/59a43c9e-0d63-4a8e-8b78-bfa266785dc7)

<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.

- jest를 사용하여 test 코드를 작성할 수 있게 되었습니다.
  <br />

2023-10-23 05:43 UTC, soheon-lee requested changes
@B3lla0 
테스트 코드가 제 로컬에서 통과가 안되는데, 테스트코드 문제가 아니라 아예 syntax에러가 나는 것 같습니다. 확인 부탁드려요! 저 10층 라운지에 있으니 대면으로 확인하셔도 됩니다 :)

<img width="1555" alt="image" src="https://github.com/wecode-bootcamp-korea/49-3rd-WEE.T-backend/assets/42701133/8e21bfdb-6413-4fb8-ab43-3c0af3269590">

2023-10-23 05:43 UTC, soheon-lee commented on src/controllers/subscribeController.js
> +const subscribeService = require("../services/subscribeService");
```suggestion
const { subscribeService } = require("../services");
```
모듈에 직접 접근 하시기 보다는 services package에서 꺼내와 보세요 :)

2023-10-23 05:43 UTC, soheon-lee commented on src/controllers/subscribeController.js
subscriptionController.js

파일 이름또한 Entity 기준으로 생성하시는게 맞아서, 동사 subscribe보다는 명사 subscription이 나을 거 같습니다.
혹시 팀내 모두 논의가 된 상황이라면 유지하셔도 좋은데, 얘기 해보시고 알려주세요!

2023-10-23 05:43 UTC, soheon-lee commented on src/models/subscribeDao.js
> +  return query;
```suggestion
const getSubscribeInfoByUserId = async (id) => {
  const query = await AppDataSource.query(
    `
    SELECT subscribes.end_date
    FROM subscribes
    JOIN users ON subscribes.id = users.id
    WHERE users.id = ?
  `,
    [id]
  );
  return query;
```

1. 함수 이름에 오타 나지 않게 스펠링 체크 잘 해주세요.
2. dao단에서 생성하는 함수의 이름은 create, read(get), update, delete 로 시작하는 것이 일반적입니다. 그리고 어떤 Entity를 조작하는지, (subscribeInfo)를 명시해 주세요.
3. SELECT할 때 필터링하는 조건이 외부 다른 entity의 id라면 함수명에 명시해 주시는 것이 좋습니다(userId). 그렇지 않고 그냥 id를 인자로 받으면 자연스럽게 subscribe의 id로 다른 개발자에게 오인되기 쉽습니다 :)

2023-10-23 05:43 UTC, soheon-lee commented on src/models/subscribeDao.js
> +    SELECT * FROM subscription;
`*` 모든 컬럼 선택자 대신, 필요한 컬럼을 정확히 명시해 주세요

2023-10-23 05:43 UTC, soheon-lee commented on src/controllers/subscribeController.js
> +const showSubscriptionPlans = async (req, res) => {
```suggestion
const getSubscriptionPlans = async (req, res) => {
```
'show' 보다는 'get'이 보다 일반적인 이름입니다 :)

2023-10-23 11:39 UTC, B3lla0 commented on src/controllers/subscribeController.js
> +const subscribeService = require("../services/subscribeService");
모듈 불러오는 방식 수정했습니다!

2023-10-23 11:56 UTC, B3lla0 commented on src/models/subscribeDao.js
> +  return query;
유의하겠습니다! 함수명 변경했습니다

2023-10-23 12:01 UTC, B3lla0 commented on src/models/subscribeDao.js
> +    SELECT * FROM subscription;
사용하는 컬럼 명시하여 반영하였습니다~!

2023-10-23 12:04 UTC, B3lla0 commented on src/controllers/subscribeController.js
> +const showSubscriptionPlans = async (req, res) => {
함수명 변경하였습니다!
+) 모듈을 잘못 불러오는 구간이 있던 탓에 테스트 코드에 오류가 있어서 수정해두었습니다!

2023-10-25 08:01 UTC, JeYeongR approved these changes

2023-10-25 08:11 UTC, soheon-lee approved these changes
!!

2023-10-25 08:12 UTC, merged