카카오 소셜로그인, 회원정보 수정 기능 구현
wecode-bootcamp-korea/49-3rd-WEE.T-backend pull request #3
Opened 2023-10-15 06:51 UTC by JeYeongR

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, <br> 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.

- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?

  passport 라이브러리를 활용하여 카카오 소셜 로그인을 구현하고, 회원 정보를 추가로 수집하기 위한 회원정보 수정 기능도 구현했습니다.

- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?

  소셜 로그인을 통해 사용자는 로그인 및 회원가입을 간편하게 완료할 수 있으며, 소셜 로그인 이후에는 회원 정보 수정 기능을 통해 추가 정보를 제공할 수 있습니다.

<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 상세 내역을 적어주세요.

카카오 소셜 로그인 기능 추가

- 이메일을 카카오한테 받아 유저를 생성
- 에세스 토큰과 리프레시 토큰을 만들어 반환함

회원 정보 수정 기능 추가

- 키 에러 검사 추가
- 닉네임이 8글자 초과인지 검사 추가
- 중복된 닉네임 검사 추가

<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. 
<br />

<img width="727" alt="image" src="https://github.com/wecode-bootcamp-korea/49-3rd-WEE.T-backend/assets/113500815/21d19cb3-8fe2-45ae-a339-9b64a53c60a6">

<img width="617" alt="image" src="https://github.com/wecode-bootcamp-korea/49-3rd-WEE.T-backend/assets/113500815/b3b0fc1f-eca7-4197-bb90-b4e11f7ac27a">

<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.

- passport 라이브러리에 대해 많이 알게 되었고, 사용법을 배웠습니다.
- 에세스 토큰과 리프레시 토큰을 어떤식으로 사용하는지 알게 되었습니다.
- 테스트 코드 작성을 할 수 있게 되었습니다.
  <br />

2023-10-16 09:09 UTC, soheon-lee requested changes
- 수고하셨습니다 :)
- Update user info는 바로 수정 반영 후 merge 가능할 것 같은데, 
- social 로그인 파트 테스트 코드 작성하시는 동안, 코드가 밀리지 않을까요?
- update user info API랑 social 로그인 API랑 PR 두 개 분리하셔서, update user info 먼저 머지할 수 있도록 하는게 어떨까요? 그래야 merge 속도가 더 빨라질 것 같습니다!

2023-10-16 09:09 UTC, soheon-lee commented on tests/user.test.js
> +    await AppDataSource.query("SET FOREIGN_KEY_CHECKS=1");
```suggestion
    await AppDataSource.query("SET FOREIGN_KEY_CHECKS=0");
    await AppDataSource.query(`TRUNCATE users`);
    await AppDataSource.query(`TRUNCATE socials`);
    await AppDataSource.query(`TRUNCATE gender`);
    await AppDataSource.query("SET FOREIGN_KEY_CHECKS=1");
```
users가 gender_id, social_id를 가지고 있는 구조 맞을까요?
FK를 가지고 있는 테이블부터 truncate하시는 것이 좋습니다 :)

2023-10-16 09:09 UTC, soheon-lee commented on tests/user.test.js
> +
1초 간격을 투고 token을 만료되게 하는 조건인가요? good!

2023-10-16 09:09 UTC, soheon-lee commented on tests/user.test.js
> +    );
```suggestion
      `
      INSERT INTO users (
        email,
        nickname,
        sns_id,
        social_id
      ) VALUES ("test2@email.com", "test nickname", 13123214, 1)
      `
    );
```

닉네임 중복 케이스를 위해서 사전에 들어가는 이름을 중복된 닉네임이라고 하신 것 같은데 맞을까요?
1. 테스트용 데이터 (fixture data 라고 합니다)는 중복의 경우에만 사용되는 것은 아니어서, 원래대로 test nickname이라고 작성하는게 좋을 것 같습니다.
2. 아래 중복 경우를 테스트하는 테스트 케이스에서 테스트 이름을 `FAIL: nickname duplicate` 라고 했기 때문에 충분히 가독성 있습니다.

2023-10-16 09:09 UTC, soheon-lee commented on src/services/userService.js
> +    endDate.setDate(startDate.getDate() + 7);
```suggestion
    const subscriptionPeriodInDays = 7;
    endDate.setDate(startDate.getDate() + subscriptionPeriodInDays);
```

7이라는 숫자의 역할을 명확히 하기 위해 변수로 선언해 주세요.

2023-10-16 09:09 UTC, soheon-lee commented on src/services/userService.js
> +    const subscribeId = subscribe.insertId;
```suggestion
    if (user.nickname !== nickname) {
      const existingUser = await userDao.findUserByNickname(nickname);
      if (existingUser) throwError(409, "DUPLICATED_NICKNAME");
    }
    
    const existingGender = await genderDao.findGenderByName(gender);
    if (!existingGender) throwError(404, "GENDER_NOT_FOUND");

    const startDate = new Date();
    const formattedStartDate = startDate.toISOString().slice(0, 10);
    const endDate = new Date(startDate);
    endDate.setDate(startDate.getDate() + 7);
    const formattedEndDate = endDate.toISOString().slice(0, 10);
    const subscribe = await subscribeDao.createSubscribe(formattedStartDate, formattedEndDate);

    const subscribeId = subscribe.insertId;
```

Gender 존재 여부를 먼저 확인해서, 없으면 날짜 formatting하는 과정도 굳이 진행할 필요 없도록 하는게 좋을 것 같습니다.

subscription용 날짜 데이터 만들다가 갑자기 gender 존재 여부를 확인하는 흐름이 다소 어색하게 느껴집니다.

2023-10-16 09:09 UTC, soheon-lee commented on src/utils/keyCheck.js
> +  });
```suggestion
  Object.keys(keysObject).forEach((key) => {
    if (!keysObject[key]) throwError(400, `KEY_ERROR: ${key}`);
  });
```

2023-10-16 10:46 UTC, JeYeongR commented on src/utils/keyCheck.js
> +  });
저렇게 하면 숫자 0이 들어오면 키에러가 발생하지 않나요?
테스트 해보니 바디에서 꺼내온 값은 숫자, 문자열 구별이 되어 문제가 발생합니다!

2023-10-16 11:42 UTC, JeYeongR commented on tests/user.test.js
> +    await AppDataSource.query("SET FOREIGN_KEY_CHECKS=1");
수정했습니다.!!

2023-10-16 11:42 UTC, JeYeongR commented on tests/user.test.js
> +    );
수정했습니다.!!

2023-10-16 11:42 UTC, JeYeongR commented on src/services/userService.js
> +    endDate.setDate(startDate.getDate() + 7);
수정했습니다.!!

2023-10-16 11:42 UTC, JeYeongR commented on src/services/userService.js
> +    const subscribeId = subscribe.insertId;
수정했습니다.!!

2023-10-17 01:56 UTC, soheon-lee commented on src/utils/keyCheck.js
> +  });
아 그렇군요, 그럼 원래 코드로 진행하면 좋을 것 같습니다! 공유해 주셔서 감사합니다 제영님-!

2023-10-17 01:56 UTC, soheon-lee approved these changes
LGTM!

2023-10-17 01:56 UTC, merged