Feature/feed
wecode-bootcamp-korea/49-3rd-WEE.T-backend pull request #9
Opened 2023-10-19 13:25 UTC by chaseunghyeok

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, <br> 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.

- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?

 홈페이지내에서 유저들간 커뮤니티 작성 및 공유 목적으로 개발하였습니다.

- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?

  유저들간 커뮤니티 소통 및 챌린지 참여를 도우며 , 서로의 식단 및 운동 사진을 공유할 수 있습니다.

<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 상세 내역을 적어주세요.

피드 추가
- 피드에 이미지 / 글 작성

피드 삭제
- 피드를 잘못올렸을 시 전체 내용 삭제
-  challenge 목적으로 올린 피드는 삭제 불가능
-  유저 아이디가 다르면 삭제 불가능 예외처리

피드 수정
- 피드를 작성 시 잘못 올린 사진 삭제 및 추가 가능 / 글 수정가능
- 피드를 작성한 유저가 아니면 수정하지 못하도록 예외처리

피드 조회
- 비회원 / 회원 모두가 조회가능
- 로그인 후 조회 시 자기 글이면 자기글인지 확인가능

랭킹 
- 글을 쓴 갯수를 토대로 랭킹을 보여줌

<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. 
<br />
<img width="960" alt="image" src="https://github.com/wecode-bootcamp-korea/49-3rd-WEE.T-backend/assets/124764329/6e6cbf8c-be27-42c5-b2c1-211960ba008c">

<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.

- 트랜잭션을 사용하므로 새로운 쿼리문 구현을 배웠습니다.
- 쿼리문에 CASE 문을 사용하여 또 다른 예외 처리 가능한것을 배웠습니다.
- 한 서비스안에 update / delete 를 묶어 사용

2023-10-19 14:45 UTC, soheon-lee requested changes
- migration 수정 사항이 API 수정과 같은 PR에 있는 것은 좋은 방법이 아닙니다 :) API 수정하느라 DB 반영이 늦어질 수 있기 때문이에요.
- migration 수정 사항은 별도의 PR로 분리해서 곧바로 다시 올려주세요! 빠르게 머지하겠습니다.
- PR이 커서 수정사항이 많은데, 꼼꼼히 확인해 주세요
- 테스트코드 작성해 주세요

2023-10-19 14:45 UTC, soheon-lee commented on src/routes/feedRouter.js
> +module.exports = feedRouter;
```suggestion
const express = require("express");
const { asyncWrap } = require("../utils/errorHandler");
const { feedController } = require("../controllers");
const feedRouter = express.Router();

feedRouter.get('', asyncWrap(feedController.getFeed));
feedRouter.post('', asyncWrap(feedController.addFeed));
feedRouter.delete('/:feedId', asyncWrap(feedController.deleteFeed));
feedRouter.put('/:feedId', asyncWrap(feedController.updateFeed));
feedRouter.delete(':feedId/:imageId', asyncWrap(feedController.updateFeed));
feedRouter.get('/rank', asyncWrap(feedController.getFeedRanking));

module.exports = feedRouter;
```

1. controller 함수 이름 뒤에 'controller' 붙이는 것은 팀내 컨벤션을 따르시면 될 것 같습니다. 현재 머지된 코드들에 controller가 뒤에 안붙어 있어서, 지우시면 좋을 것 같아요 :) 팀내 컨벤션이 변경되었다면 알려주세요!
2. delete메소드에 왜 updateFeedController가 연결되어 있나요??
3. userId는 uri에서 받아오시면 안되고, token에서 받아오셔야 합니다.
4. imageURL을 수정하시고자 한다면 request body에서 받아오시는 것이 좋을 것 같습니다.

2023-10-19 14:45 UTC, soheon-lee commented on src/services/feedService.js
> +const { findUserById } = require("../models/userDao");
```suggestion
const { userDao } = require("../models");
```

2023-10-19 14:45 UTC, soheon-lee commented on src/controllers/feedController.js
> +    const offset = (page -1) * limit
- limit, offset도 프론트에서 query string으로 받아오는 것이 일반적입니다.
- 프론트에서 받아올 수 없다면, 위 page 변수처럼 기본값을 부여하여 주세요 :)

2023-10-19 14:45 UTC, soheon-lee commented on src/controllers/feedController.js
> +    console.log(page, offset);
콘솔로그 지워주세요

2023-10-19 14:45 UTC, soheon-lee commented on src/controllers/feedController.js
> +    const getFeed = await feedService.getFeedService(userId, limit, offset, page);
```suggestion
    const feedData = await feedService.getFeedsByUserId(userId, limit, offset, page);
```
- 변수는 동사가 아닌 명사형으로 네이밍 하는 것이 일반적인 컨벤션입니다. 변수는 어떤 행동을 하지 않기 때문입니다.

2023-10-19 14:45 UTC, soheon-lee commented on src/controllers/feedController.js
> +    res.status(200).json({
```suggestion
    res.status(201).json({
```

2023-10-19 14:45 UTC, soheon-lee commented on src/controllers/feedController.js
> +};
```suggestion
    res.status(204).json({
        message : "DELETE_SUCCESS",
        data : deleteFeed,
    });
};
```

2023-10-19 14:45 UTC, soheon-lee commented on src/controllers/feedController.js
> +
불필요한 공백 제거해 주세요

2023-10-19 14:45 UTC, soheon-lee commented on src/models/feedDao.js
> +                [userId, content, isChallenge]
```suggestion
                [userId, content, challenge]
```
혹시 isChallenge 변수 선언 안하고, 곧바로 challenge 넣으면 어떻게 되나요?

2023-10-19 14:45 UTC, soheon-lee commented on src/models/feedDao.js
> +    const deleteFeeds = async(feedId, userId, challenge) => {
```suggestion
    const deleteFeeds = async(feedId) => {
```
- feedId 자체가 primary key로 유일한 고유값이기 때문에, 지울 때는 키 하나만 있어도 됩니다 다른 변수는 비교할 필요 없을 것 같습니다 :)

2023-10-19 14:45 UTC, soheon-lee commented on src/models/feedDao.js
> +    }
```suggestion
    const getFeedByUserId = async(userId) => {
        const feed = await AppDataSource.query(`
            SELECT
                id, 
                user_id
            FROM
                feeds
            WHERE user_id = ?
        `,
            [userId]
        );
        return feed
    }
```
- 상황에 적절한 함수명 지어주세요

2023-10-19 14:45 UTC, soheon-lee commented on src/models/feedDao.js
> +    }
```suggestion
    const feedRankingByFeedCount = async () => {
        const ranking = await AppDataSource.query(`
            SELECT
                users.nickname AS nickname,
                b.image_url AS badge,
                COUNT(feeds.id) AS feed_count
            FROM
                users
            LEFT JOIN
                feeds ON users.id = feeds.user_id
            LEFT JOIN
                badges b ON users.badge_id = b.id
            GROUP BY
                users.id
            ORDER BY
                feed_count DESC;
        `)
        return ranking;
    }
```

2023-10-19 14:45 UTC, soheon-lee commented on src/services/feedService.js
> +    if (page < 1) throwError(400, "PAGE_STARTS_FROM_ONE");
```suggestion
    
```

- 이 조건문은 잘못된 조건문이에요~
- 왜냐하면 백엔드에서는 client가 지금 몇 페이지를 누르고 요청을 보내는지 알 수 없고, 1페이지 부터 보는지  알 수 없습니다. 각각의 HTTP request가 독립적이기 때문입니다. 이건 frontend에서 backend에 1페이지부터 데이터를 요청해야한다고 강제하기 위해서 작성하셨을 것 같은데, 백엔드는 frontend가 연속적으로 요청을 보내는지 파악할 수 없습니다 :) 그리고 파악해서도 안되어요!
- 이것이 HTTP의 stateless 특징입니다. 각각의 요청은 독립이다.

2023-10-19 14:45 UTC, soheon-lee commented on src/services/feedService.js
> +    const feedCount = await feedDao.getFeedCount();
```suggestion
    const feedList= await feedDao.getFeeds(userId, limit, offset);
    const feedCount = await feedDao.getFeedCount();
```

2023-10-19 14:45 UTC, soheon-lee commented on src/services/feedService.js
> +    const feeds = Array.isArray(getFeedList) ? getFeedList : [getFeedList] ;
feed 데이터 늘 Array아닌가요?? 데이터가 1개 밖에 없더라도 typeORM에서 SELECT문 실행시 자동으로 배열로 만드는 걸로 알고 있습니다. 이거 확인해보고, 피드 리스트 1개일 때랑 여러개일 때랑 console.log찍으면 어떻게 나오는지 캡쳐하셔서 아래에 사진으로 첨부해주세요~

2023-10-19 14:45 UTC, soheon-lee commented on src/services/feedService.js
> +    }
이 조건문은 이미지가 4개인 경우는 허용하게 됩니다. 수정해 주세요~ :)

2023-10-20 08:44 UTC, chaseunghyeok commented on src/routes/feedRouter.js
> +module.exports = feedRouter;
네! controller 수정하였고 , delete 메소드는 잘못 적은거로 지우며 수정했습니다!
userId는 넣어보고 해보았고, token값으로 받아오는걸로 수정하겠습니다.
imageURL req.body 변경완료하였습니다.

2023-10-20 08:44 UTC, chaseunghyeok commented on src/services/feedService.js
> +const { findUserById } = require("../models/userDao");
findUserById는 잘못된 임포트로 지우는걸로 수정하였습니다.

2023-10-20 08:44 UTC, chaseunghyeok commented on src/controllers/feedController.js
> +    const offset = (page -1) * limit
네 변경하였습니다!

2023-10-20 08:44 UTC, chaseunghyeok commented on src/controllers/feedController.js
> +    console.log(page, offset);
불필요한 콘솔로그 제거 완료하였습니다

2023-10-20 08:44 UTC, chaseunghyeok commented on src/controllers/feedController.js
> +    const getFeed = await feedService.getFeedService(userId, limit, offset, page);
네 ! 변경하였습니다 !

2023-10-20 08:45 UTC, chaseunghyeok commented on src/controllers/feedController.js
> +    res.status(200).json({
수정하였습니다. 응답코드 신경쓰도록 하겠습니다!

2023-10-20 08:45 UTC, chaseunghyeok commented on src/controllers/feedController.js
> +};
수정하였습니다.

2023-10-20 08:45 UTC, chaseunghyeok commented on src/controllers/feedController.js
> +
공백 제거 완료. 신청 쓰도록하겠습니다.

2023-10-20 08:45 UTC, chaseunghyeok commented on src/models/feedDao.js
> +                [userId, content, isChallenge]
0이나 1 선언한 값이 들어갑니다!
이 부분은 프론트랑 맞춰보고 어떻게 들어가는지 다시 한 번 검토해보겠습니다!

2023-10-20 08:45 UTC, chaseunghyeok commented on src/models/feedDao.js
> +    const deleteFeeds = async(feedId, userId, challenge) => {
네! 지우고 수정했습다

2023-10-20 08:45 UTC, chaseunghyeok commented on src/models/feedDao.js
> +    }
네 피드아이디 찾는걸로 변경 하였습니다!

2023-10-20 08:45 UTC, chaseunghyeok commented on src/models/feedDao.js
> +    }
네! 변경하였습니다.

2023-10-20 08:45 UTC, chaseunghyeok commented on src/services/feedService.js
> +    if (page < 1) throwError(400, "PAGE_STARTS_FROM_ONE");
네 ! 숙지하겠습니다 !

2023-10-20 08:45 UTC, chaseunghyeok commented on src/services/feedService.js
> +    const feedCount = await feedDao.getFeedCount();
네 변경하였습니다 !

2023-10-20 08:45 UTC, chaseunghyeok commented on src/services/feedService.js
> +    const feeds = Array.isArray(getFeedList) ? getFeedList : [getFeedList] ;
- 1개일 때
<img width="389" alt="image" src="https://github.com/wecode-bootcamp-korea/49-3rd-WEE.T-backend/assets/124764329/d7d7aa38-d6ee-4b7e-9aa6-8fa562fc8db6">

- 여러개 일 때
<img width="421" alt="image" src="https://github.com/wecode-bootcamp-korea/49-3rd-WEE.T-backend/assets/124764329/fdda5ea9-e266-4860-acfb-25a407fb661f">

배열로 나오는 거 확인 후 수정하였습니다!

2023-10-20 08:45 UTC, chaseunghyeok commented on src/services/feedService.js
> +    }
네 수정하였습니다

2023-10-20 11:40 UTC, soheon-lee commented
수정 사항 빠르게 반영해 주셔서 감사합니다! :) 테스트 코드 추가해 주세요~

2023-10-25 03:15 UTC, JeYeongR approved these changes

2023-10-25 03:19 UTC, JeYeongR approved these changes

2023-10-25 07:43 UTC, soheon-lee approved these changes

2023-10-25 07:43 UTC, soheon-lee commented on .env.test
.env.test도 현재 github에 노출되어서는 안됩니다 :) 파일 숨겨주세요

2023-10-25 07:43 UTC, soheon-lee commented on src/controllers/feedController.js
> +    const user = req.user.id;
```suggestion
    const user = req.user.id;
    const { content, challenge, imageUrl } = req.body;
```
유저 정보를 먼저 꺼내오는 것이 보다 일반적인 순서입니다 :)

2023-10-25 07:43 UTC, soheon-lee commented on src/controllers/feedController.js
> +    const user = req.user.id;
```suggestion
    const { content, challenge, imageUrl } = req.body;
    const userId = req.user.id;
```

2023-10-25 07:54 UTC, merged